name: Daily Project Metrics Generation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC
  workflow_dispatch:

jobs:
  generate_and_commit_metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  
      - name: Checkout INSO GH Metrics code
        uses: actions/checkout@v4
        with:
          repository: Poggecci/INSO-GH-API-QUERY
          path: inso-gh-query-metrics

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

    
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      
      - name: Configure Poetry
        run: |
          cd inso-gh-query-metrics
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

    
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: inso-gh-query-metrics/.venv
          key: venv-${{ hashFiles('inso-gh-query-metrics/poetry.lock') }}

     
      - name: Install dependencies
        run: |
          cd inso-gh-query-metrics
          poetry install
        shell: bash

     
      - name: Run metrics generator
        run: |
          cd inso-gh-query-metrics
          poetry run python src/generateMilestoneMetricsForActions.py \
            ${{ github.workspace }}/gh_metrics_config.json
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
        shell: bash

     
      - name: Move Generated Metrics
        run: |
          mkdir -p metrics
          mv inso-gh-query-metrics/*${{ github.repository_owner }}*.md metrics/
        shell: bash

     
      - name: Pull latest changes
        run: git pull --rebase origin main

   
      - name: Auto Commit Results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Automated] Milestone Metrics Update"
          file_pattern: metrics/*.md
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          commit_author: GitHub Action <action@github.com>
